### ISSUE TITLE
retry upstream connection

### ISSUE THREAD

**Issue by danieleades** [fullstorydev/grpcui#101]
I'm using grpcui in a docker-compose app. I've got a bit of a race condition where the upstream gRPC server often doesn't start before grpcui attempts to connect to it. I'm using docker-compose `depends_on`, but this doesn't work because the container with the gRPC service reports ready when the server process has started, and not when the server is actually ready to receive connections. There's normally a few seconds in it.

Grpcui is making one attempt to connect to the upstream service, and then exiting with an error code. What i'd really like is a way to specify that it should retry the upstream connection. Is there a clean way to do this?

**Comment by danieleades** [comment]
note that `-connect-timeout` doesn't do the trick.

I get 'failed to dial target host... connection refused'

**Comment by danieleades** [comment]
and here is the `-vv` output-

```
grpc-ui_1      | INFO: 2020/11/12 13:08:58 parsed scheme: ""
grpc-ui_1      | INFO: 2020/11/12 13:08:58 scheme "" not registered, fallback to default scheme
grpc-ui_1      | INFO: 2020/11/12 13:08:58 ccResolverWrapper: sending update to cc: {[{UPSTREAM_SERVICE:50051  <nil> 0 <nil>}] <nil> <nil>}
grpc-ui_1      | INFO: 2020/11/12 13:08:58 ClientConn switching balancer to "pick_first"
grpc-ui_1      | INFO: 2020/11/12 13:08:58 Channel switches to new LB policy "pick_first"
grpc-ui_1      | INFO: 2020/11/12 13:08:58 Subchannel Connectivity change to CONNECTING
grpc-ui_1      | INFO: 2020/11/12 13:08:58 Subchannel picks a new address "UPSTREAM_SERVICE:50051" to connect
grpc-ui_1      | INFO: 2020/11/12 13:08:58 Channel Connectivity change to CONNECTING
grpc-ui_1      | WARNING: 2020/11/12 13:08:58 grpc: addrConn.createTransport failed to connect to {UPSTREAM_SERVICE:50051  <nil> 0 <nil>}. Err: connection error: desc = "transport: error while dialing: dial tcp 172.18.0.2:50051: connect: connection refused". Reconnecting...
grpc-ui_1      | INFO: 2020/11/12 13:08:58 Subchannel Connectivity change to TRANSIENT_FAILURE
grpc-ui_1      | INFO: 2020/11/12 13:08:58 Channel Connectivity change to TRANSIENT_FAILURE
grpc-ui_1      | INFO: 2020/11/12 13:08:58 Channel Connectivity change to SHUTDOWN
grpc-ui_1      | INFO: 2020/11/12 13:08:58 Subchannel Connectivity change to SHUTDOWN
grpc-ui_1      | Failed to dial target host "UPSTREAM_SERVICE:50051": dial tcp 172.18.0.2:50051: connect: connection refused
```

**Comment by jhump** [comment]
This behavior comes from the ad-hoc/CLI use case. When I first wrote it, I didn't anticipate how broadly it would be used as a long-running service/sidecar.

I think we need to add a `-wait-for-connect` flag that defaults to true. And when it's false, we don't use the `BlockingDial` function that it currently uses, but instead does a normal `grpc.Dial` (with no blocking option).

The downside not waiting/blocking for the connection is that non-transient errors (like misconfigured TLS settings) will never "heal" and would mean the grpcui server remains broken until it is stopped and re-started with different parameters.

**Comment by troyswanson** [comment]
I'm having the exact same issue. @danieleades, I would love to hear about what your solve for this was.

**Comment by danieleades** [comment]
> I'm having the exact same issue. @danieleades, I would love to hear about what your solve for this was.

My solution was to wrap up that project and move onto another one...

Would be nice to see a resolution though, running grpcui as a sidecar to a development environment is a handy use-case

**Comment by jhump** [comment]
I'd be happy to review a PR in the vein of my suggestion above, if you're up for it, @troyswanson.

**Comment by troyswanson** [comment]
Go is not my strength, but I’ll see if I can figure it out.

**Comment by troyswanson** [comment]
I've made a patch and merge request that solves this issue.
