### ISSUE TITLE
Use -default-header values during reflection call

### ISSUE THREAD

**Issue by niya3** [fullstorydev/grpcui#111]
`grpcui` tries to reflect services by itself when proto-files aren't provided. But it if the server requirers some authorization headers, then user should provide them both via `-reflect-header` (for reflection) and `-default-header` (for connection) flags. Wouldn't it be handy if -default-header values were automatically added to [reflection call metadata](https://github.com/fullstorydev/grpcui/blob/2e37f255eaec8028cf1bbf761965ed94d4d8885d/cmd/grpcui/grpcui.go#L348)?

**Comment by jhump** [comment]
You can now use a `-H` option (like curl's option), which defines headers used for all requests (both RPC invocation _and_ reflection requests).
