### ISSUE TITLE
Documentation for installation should be updated

### ISSUE THREAD

**Issue by dliedke** [fullstorydev/grpcui#119]
If following the current steps for installation it is failing:

>go install github.com/fullstorydev/grpcui/cmd/grpcui
go install: version is required when current directory is not in a module
        Try 'go install github.com/fullstorydev/grpcui/cmd/grpcui@latest' to install the latest version

My suggestion is to update the documentation:

You can use the go tool to install grpcui:

go get github.com/fullstorydev/grpcui/...
**go install github.com/fullstorydev/grpcui/cmd/grpcui@latest**

**Comment by hojongs** [comment]
I agree with you so I've made PR :)

**Comment by jhump** [comment]
Hmm, I think the issue is that it depends on the version of Go you are using. I think they've made changes in Go 1.16 related to this. @dliedke, @hojongs: are you using Go 1.16? If not, what version of Go were you using when you encountered this issue?

**Comment by dliedke** [comment]
@jhump using go1.16.4 thanks!
