### ISSUE TITLE
Error when storing large responses in history

### ISSUE THREAD

**Issue by kodedylf** [fullstorydev/grpcui#124]
When calling a service that returns a large response, gRPCui fails when storing the call in the history. No error message is shown and neither is the response.

The error in the browser console is
```
Uncaught DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'grpcui-history-localhost:60551-host.docker.internal:8017' exceeded the quota.
    at onHistoryChange (http://localhost:60551/grpc-web-form.js:2431:22)
    at addHistory (http://localhost:60551/grpc-web-form.js:2445:9)
    at Object.<anonymous> (http://localhost:60551/grpc-web-form.js:2199:21)
    at c (http://localhost:60551/jquery-3.4.1.min.js:2:27742)
    at Object.fireWith [as resolveWith] (http://localhost:60551/jquery-3.4.1.min.js:2:28487)
    at l (http://localhost:60551/jquery-3.4.1.min.js:2:78789)
    at XMLHttpRequest.<anonymous> (http://localhost:60551/jquery-3.4.1.min.js:2:81117)
```

**Comment by hvdbrand** [comment]
We see very similar behavior on Firefox 89.0.2 (64-bit) using a grpcui devbuild (Installed using https://github.com/fullstorydev/grpcui/blob/master/README.md#from-source a few months back)

We have a grpc interface that has a function to return images which have a size of about 1.3 MB.
When we call that function the first two calls work as expected.
On the third call we seem to never get a response and the developer console displayed the DOM exception below: 
```
Uncaught DOMException: The quota has been exceeded. grpc-web-form.js:2431
    onHistoryChange http://127.0.0.1:59320/grpc-web-form.js:2431
    addHistory http://127.0.0.1:59320/grpc-web-form.js:2445
    invoke http://127.0.0.1:59320/grpc-web-form.js:2199
    jQuery 6
    invoke http://127.0.0.1:59320/grpc-web-form.js:2120
    initGRPCForm http://127.0.0.1:59320/grpc-web-form.js:2589
    jQuery 2
```

I think it would be nice to have some feedback about the error.
Some resolutions I can think of are:
* Changing the storage size of the browser. I was not able to find if this is possible for firefox.
* A command line option to disable command history.
* Catch storage exception and handle it by logging and no further processing.
