### ISSUE TITLE
On-fly default headers

### ISSUE THREAD

**Issue by augi** [fullstorydev/grpcui#126]
We would like to be able to call service with JWT-based authentication. We are using `-default-header` command-line parameter, and the issue is that it just prefills the value in the web form, so the value is obviously not updated in the web form after the server gets restarted with a new default header.

To better describe the situation, this is entrypoint of our Docker container (that is `FROM` grpcui):
```sh
#!/bin/sh
while true
do
  TOKEN=$(curl -s -X POST https://${KEYCLOAK_HOST:-our.keycloak.company.com}/auth/realms/${REALM:-master}/protocol/openid-connect/token -H "Content-Type: application/x-www-form-urlencoded" -d "username=${USERNAME}" -d "password=${PASSWORD}" -d 'grant_type=password' -d "client_id=${CLIENT_ID:-cli}" | jq -r '.access_token')
  timeout ${TIMEOUT:-300} /usr/bin/grpcui -bind=0.0.0.0 -port=${PORT:-8080} -default-header "Authorization: Bearer $TOKEN" "$@"
done
```
So it restarts the grpcui server every 5 minutes (expiration of the token). The obviously bad thing is that `-default-header` just prefills the value in the web form, so the server restart has no effect. What would help would be if there were a `-hidden-default-header` argument that wouldn't be passed to the web form. Instead, it would be automatically appended by the grpcui server (probably in the `/invoke` handler), if not explicitly specified by the user.

For the record, this is the `Dockerfile`:
```dockerfile
FROM fullstorydev/grpcui:v1.1.0 AS grpcui
FROM alpine:3.13.5
COPY --from=grpcui /bin/grpcui /usr/bin/grpcui
RUN apk update && apk add jq curl && rm -rf /var/cache/apk/*
COPY entrypoint.sh ./
ENTRYPOINT ["/entrypoint.sh"]
```

**Comment by jhump** [comment]
New options have been added for "hidden" headers -- metadata that is added to the request but is not shown in the UI form.

For consistency with grpcurl, the options are named `-H` (like curl) and `-rpc-headers`. The former are added to all requests, which includes reflection requests.

**Comment by augi** [comment]
Thank you, awesome! 👍
