### ISSUE TITLE
unable to send google.protobuf.Timestamp in Safari

### ISSUE THREAD

**Issue by Gurpartap** [fullstorydev/grpcui#127]
<img width="665" alt="Screenshot 2021-06-23 at 03 17 19" src="https://user-images.githubusercontent.com/39792/123003929-86e96380-d3d1-11eb-84e9-4640b7b2057e.png">

It fails validation in UI, and sends epoch 0 time on server.

Works in Chrome though.

Tried both `github.com/fullstorydev/grpcui v1.1.0` and `github.com/fullstorydev/grpcui v1.1.1-0.20210615152741-73d509c2f2ba` (master as of today).

Safari Version 14.1 (16611.1.21.161.6)
macOS 11.3.1 (20E241)

Side question, is there a way to restore the htmlized response structure UI (as was in previous versions)?

**Comment by jhump** [comment]
Fixed in #159.
