### ISSUE TITLE
How to work it?

### ISSUE THREAD

**Issue by HakunamatataLeo** [fullstorydev/grpcui#132]
` ./grpcui -plaintext localhost:2233
Failed to dial target host "localhost:2233": dial tcp 127.0.0.1:2233: connect: connection refused`

**Comment by jhump** [comment]
@HakunamatataLeo, not enough info for me to go on, sorry. You have to give it the host+port of a valid gRPC server. The server needs to expose the [reflection service](https://github.com/grpc/grpc/blob/master/doc/server-reflection.md#known-implementations), too, unless you provide proto sources for your RPC schema (via `-proto` args).

Please take a look through the [README](https://github.com/fullstorydev/grpcui/blob/master/README.md).
