### ISSUE TITLE
Support `optional` field label

### ISSUE THREAD

**Issue by mcquackers** [fullstorydev/grpcui#140]
As part of [protobuf 3.15.0](https://github.com/protocolbuffers/protobuf/releases/tag/v3.15.0), the protocol buffer language supports the `optional` field label.

Trying connect to a grpc server that doesn't support reflection, so requiring the .proto files themselves, results in 
`Failed to process proto source files.: could not parse given files: path/to/file.proto:29:5: field Message.field: field has label LABEL_OPTIONAL, but proto3 must omit labels other than 'repeated'`

It'd be nice if GRPC UI supported this language specification.

**Comment by jhump** [comment]
@mcquackers, I assume you are using a released version This is actually resolved on master, if you want to try it out/use latest master as a workaround. We'll cut a release soon so the fix gets out into a release build.

**Comment by mcquackers** [comment]
@jhump Awesome to hear, thanks!
