### ISSUE TITLE
Make it possible to configure the port when using the docker image

### ISSUE THREAD

**Issue by LanDinh** [fullstorydev/grpcui#147]
Hi all,

I really like that you offer a ready-built docker image - what I don't like about it is that you hard-code the port at which grpcui gets exposed. It's fine when using raw docker, in which case it's possible to map the port to whatever you want - but it gets a bit more complicated when using grpcui as sidecar container in kubernetes :D This would be a nice workaround until #14 is resolved.

Full background:
I'm running an ecosystem of microservices. For development environments, I want to add grpcui to all of them. Since at least for now, grpcui supports only a single grpc service, I need as many instances of grpcui as I have microservices. There's two options here:

* Create a full-blown kubernetes deployment for each grpcui instance to manage the pod that grpcui will run in
* Add grpcui as *sidecar* container to the existing pods / deployments I have for my microservices

Option 1 would be a lot more overhead. Option 2 puts the service, as well as any other sidecars they might have (e.g. envoy for those services that need to be accessible to grpc-web) onto the same docker network as grpcui - meaning that there might be port clashes. I don't like having to adapt my port assignments of all already-existing containers to whatever grpcui decides to use in its own Dockerfile ;)

There should of course be a default port in case none is specified for all those who don't care, but it would be great to choose the port, e.g. through an environment variable! That way, I can simply pass that environment variable in my kubernetes manifest and get the port I want without breaking with my existing port-scheme to avoid port clashes inside pods (e.g. everything 8XXX is what is necessary itself for the service to exist, 9XXX is anything development / debugging related)

**Comment by jhump** [comment]
I don't think this is a problem. You can already supply a different port via command-line arg to the container. If you supply `-port=1234`, for example, that will override the default port. Does that not work for you? (I just tried it locally and am pretty sure it should work for you, too.)

**Comment by LanDinh** [comment]
That was stupid of me xD I did not think about providing the same argument multiple times to have the last instance of it count.... Thanks!
