### ISSUE TITLE
Disable connect fail fast, is it possible?

### ISSUE THREAD

**Issue by sbchisholm** [fullstorydev/grpcui#150]
With the `-connect-fail-fast` defaulting to `true` from what I can tell there isn't a way to pass the flag so that it becomes `false`. If there isn't a way to make this `false` perhaps we could rename it to `-no-connect-fail-fast` and have it `false` by default.

```
	connectFailFast = flags.Bool("connect-fail-fast", true, prettify(`
		If true, non-temporary errors (such as "connection refused" during
		initial connection will cause the program to immediately abort. This
		is the default and is appropriate for interactive uses of grpcui. But
		long-lived server use (like as a sidecar to a gRPC server) will prefer
		to set this to false for more robust startup.`))
```

**Comment by jhump** [comment]
> from what I can tell there isn't a way to pass the flag so that it becomes false

This is not true: `-connect-fail-fast=false`

**Comment by jhump** [comment]
https://pkg.go.dev/flag#hdr-Command_line_flag_syntax

**Comment by sbchisholm** [comment]
Ah, thanks @jhump.  I had tried `-connect-fail-fast false`, which didn't work but I see they mention this in their docs:

> -flag
> -flag=x
> -flag x  // non-boolean flags only
