### ISSUE TITLE
Command-line options to set max message size for channel

### ISSUE THREAD

**Issue by raymondle** [fullstorydev/grpcui#17]
Hi everyone,
I'm trying to get ByteString from server with content length is larger than max (6221671 vs. 4194304). With client in C# i'm using ChannelOptions with key is `grpc.max_receive_message_length` to set max length and can receive large file from Server. So in grpcUI how can i do that?

Thank for your help.

**Comment by jhump** [comment]
I think we need command-line options to set some of those options when the RPC client is created. (Though I must confess, examining a 6mb byte string response doesn't seem like a great fit for a web UI like this tool.)

**Comment by raymondle** [comment]
Hi @jhump, I agree with you about it. But I think we need a tool for testing stream file.
