### ISSUE TITLE
go install grpcui is giving below errors

### ISSUE THREAD

**Issue by dduraisa** [fullstorydev/grpcui#182]
(base) dineshkumar@Dineshs-MacBook-Pro-2 ~ % go install github.com/fullstorydev/grpcui/cmd/grpcui@latest
# golang.org/x/sys/unix
go/pkg/mod/golang.org/x/sys@v0.0.0-20200331124033-c3d80250170d/unix/syscall_darwin.1_13.go:25:3: //go:linkname must refer to declared function or variable
go/pkg/mod/golang.org/x/sys@v0.0.0-20200331124033-c3d80250170d/unix/zsyscall_darwin_arm64.1_13.go:27:3: //go:linkname must refer to declared function or variable
go/pkg/mod/golang.org/x/sys@v0.0.0-20200331124033-c3d80250170d/unix/zsyscall_darwin_arm64.1_13.go:40:3: //go:linkname must refer to declared function or variable
go/pkg/mod/golang.org/x/sys@v0.0.0-20200331124033-c3d80250170d/unix/zsyscall_darwin_arm64.go:28:3: //go:linkname must refer to declared function or variable
go/pkg/mod/golang.org/x/sys@v0.0.0-20200331124033-c3d80250170d/unix/zsyscall_darwin_arm64.go:43:3: //go:linkname must refer to declared function or variable
go/pkg/mod/golang.org/x/sys@v0.0.0-20200331124033-c3d80250170d/unix/zsyscall_darwin_arm64.go:59:3: //go:linkname must refer to declared function or variable
go/pkg/mod/golang.org/x/sys@v0.0.0-20200331124033-c3d80250170d/unix/zsyscall_darwin_arm64.go:75:3: //go:linkname must refer to declared function or variable
go/pkg/mod/golang.org/x/sys@v0.0.0-20200331124033-c3d80250170d/unix/zsyscall_darwin_arm64.go:90:3: //go:linkname must refer to declared function or variable
go/pkg/mod/golang.org/x/sys@v0.0.0-20200331124033-c3d80250170d/unix/zsyscall_darwin_arm64.go:105:3: //go:linkname must refer to declared function or variable
go/pkg/mod/golang.org/x/sys@v0.0.0-20200331124033-c3d80250170d/unix/zsyscall_darwin_arm64.go:121:3: //go:linkname must refer to declared function or variable
go/pkg/mod/golang.org/x/sys@v0.0.0-20200331124033-c3d80250170d/unix/zsyscall_darwin_arm64.go:121:3: too many errors
(base) dineshkumar@Dineshs-MacBook-Pro-2 ~ %

**Comment by mi1wei** [comment]
怎么解决 的

**Comment by zhaolie1989** [comment]
我也碰到了这个问题

**Comment by dduraisa** [comment]
The issue got resolved after doing brew install grpcui
