### ISSUE TITLE
must restart grpcui when connection to server is lost

### ISSUE THREAD

**Issue by jhump** [fullstorydev/grpcui#21]
If I start both grpcui and a gRPC server and then have to restart the gRPC server, the grpcui program gets into a bad state and must also be restarted.

The problem is due to the use of the original dial context in the custom dialer (in grpcurl's `BlockingDial` function), even for subsequent connect operations. So when the gRPC client in grpcui tries to re-establish a connection, it is using an expired context and so can never successfully reconnect.

This is fixed in the latest version of grpcurl. So we need a new release of grpcurl so that grpcui can depend on it in its `go.mod` file.

**Comment by PatrLind** [comment]
This still seems to be an issue if the server panics or if the connection isn't shut down correctly.

**Comment by jhump** [comment]
@PatrLind, that appears to be a different issue due to this part of the error message:
```
No connection could be made because the target machine actively refused it.
```
I suspect that is caused by a failure to reconnect when the server *was* down, and then RPC client using exponential backoff before re-trying to connect. So you may have caught it after its connection attempt was refused but before it re-tried the connection.

So I don't think grpcui needed to be restarted -- I think perhaps you needed to wait a little longer for the connection to heal. If you can try to verify that and if that's the case (it does eventually heal), file it as a different bug. If it never heals, try using `-vv` logging options and include the log output.

**Comment by PatrLind** [comment]
Thanks! I'll try that!
