### ISSUE TITLE
Can't work with proto definitions that include includes external proto definitions.

### ISSUE THREAD

**Issue by sayantanvlabs** [fullstorydev/grpcui#215]
We have a proto definition that includes import from external package,
```
import "github.com/XYZGroup/xyz-frogpoint-types/frogpoint-types.proto";
import "github.com/XYZGroup/xyz-booking/booking.proto";
```
Starting the grpcui server gives me error:
`grpcui -port 9002 -plaintext -proto=crewchange.proto -import-path=d:/Projects/XYZ localhost:2040`

For reference, `d:/Projects/XYZ` is the parent directory to all the project related repositories.

The error I am getting is:
> Failed to process proto source files.: could not parse given files: xyz-crewchange/crewchange.proto:5:8: github.com/XYZGroup/xyz-frogpoint-types/frogpoint-types.proto: open d:\Projects\XYZ\github.com\XYZGroup\xyz-frogpoint-types\frogpoint-types.proto: The system cannot find the path specified.

**Comment by jhump** [comment]
Do you mean that all repos under `github.com/XYZGroup` are checked out under `d:/Projects/XYZ`? How do you actually _build_ this stuff (like to generate your client and server code) such that the proto compiler can find these imports?

I see you're working in Windows, so not sure how feasible this is, but if the file system supports sym-links, you could create a directory named `d:/Projects/github.com/XYZGroup` that is a sym-link to `d:/Projects/XYZ` maybe.

If you _do_ have those projects checked out somewhere that already gas `github.com/XYZGroup/` directory parents, then you just need to point `grpcui` at that other folder with a `-import-path` flag.

**Comment by sayantanvlabs** [comment]
Ahh, got it. We use go module's vendoring during building. So adding and `-import-path` to the vendor folder worked smoothly. Closing the issue now. Thanks.
