### ISSUE TITLE
where is the docker image hosted?

### ISSUE THREAD

**Issue by muhlemmer** [fullstorydev/grpcui#247]
Thanks for this awesome project!

Is there an automatic Docker image build and there would the resulting image be hosted? I could only find https://hub.docker.com/r/fullstorydev/grpcui, with a push more than 10 months ago.

**Comment by jhump** [comment]
That's the correct one. There hasn't been a release since last August, v1.3.1:

https://github.com/fullstorydev/grpcui/releases

**Comment by dragonsinth** [comment]
I guess we should probably do another release?

**Comment by muhlemmer** [comment]
aah, my bad. Thanks

**Comment by conorsch** [comment]
It's been about 11 months since the last release. Any traction on tagging current main, and potentially updating the container image to match?

**Comment by bschaeffer** [comment]
We've since released [1.3.2](https://github.com/fullstorydev/grpcui/releases/tag/v1.3.2) and [1.3.3](https://github.com/fullstorydev/grpcui/releases/tag/v1.3.3). Should we close this?
