### ISSUE TITLE
Javascript validation broken for negative integers

### ISSUE THREAD

**Issue by Jamie-Chang** [fullstorydev/grpcui#27]
It looks like the javascript function `compareStringInts` compares the absolute value when both values are negative, which causes the validation error here:

![image](https://user-images.githubusercontent.com/10587281/54942494-1b309b80-4f27-11e9-98d3-48eb9fc6406b.png)

**Comment by jhump** [comment]
PR #29 did not actually fix this issue. My bad.

But a real fix can be found in #31, so this will finally be fixed soon.

**Comment by jhump** [comment]
This was fixed in PR #31. I plan on making a new release with this and some other fixes in the coming week.
