### ISSUE TITLE
Can't use negative values on int64

### ISSUE THREAD

**Issue by facundomedica** [fullstorydev/grpcui#30]
I can see in my local machine the commit (#29) that should fix this but I can't get it to work. I've tried deleting and installing again, but nothing works. Am I missing something?

```
facundo:grpcui facundomedica$ git log
commit 20f41010374fb569638f2d094776e27ffd1a0634 (HEAD -> master, origin/master, origin/HEAD)
Author: Joshua Humphries <jh@fullstory.com>
Date:   Tue Mar 26 14:46:20 2019 -0400

    fix range validation for 64-bit signed ints (#29)
```

**Comment by jhump** [comment]
After making sure you've updated to that sha and recompiled, if it still happens, do you mind sending me a sample proto file and steps to reproduce (e.g. which field and what value to try)? Maybe there's something subtle I missed such that my earlier fix isn't correctly applied to all manner of signed ints... Having a repro case would help me find it.

**Comment by facundomedica** [comment]
@jhump sorry for the delay, here you go. It's weird, because an `int32` can be set as negative but `int64` can't

```
syntax = "proto3";
option go_package = "admin";
package admin;
import "google/protobuf/empty.proto";

service Admin {
    rpc SomeService(SomeMessage) returns (google.protobuf.Empty) {}
}
message SomeMessage {
  string user_id = 1;
  int64 amount = 2; // in this field I get the error
  int32 currency = 3; // but this one can be negative with no complains
  string message = 4;
}
```

**Comment by jhump** [comment]
@facundomedica, thanks for that. I was able to reproduce. Apparently, I totally failed when I pushed the supposed fix. Real fix incoming...
