### ISSUE TITLE
Release v1 reflection changes as 1.4.2

### ISSUE THREAD

**Issue by conorsch** [fullstorydev/grpcui#322]
The most recent published release, 1.4.1, does not support the `grpc.reflection.v1alpha.ServerReflection` -> `grpc.reflection.v1.ServerReflection` changes from https://github.com/fullstorydev/grpcui/pull/314. Our project recently updated to v1, and in the process, lost introspection via grpcui.

Could we get a tagged release for 1.4.2, flushing the current contents of main, as well as a new container build? 

The workaround in the meantime is to build from source. At time of writing, commit 483f037ec98b89200353c696d990324318f8df98 worked great for supporting v1 reflection. 

Many thanks for the great project!

**Comment by kanpov** [comment]
Any update on this?

**Comment by dragonsinth** [comment]
@gpassini anyone over there wanna cut a new release? it has been a while now.

**Comment by gpassini** [comment]
@dragonsinth good point, I can cut a release today.

**Comment by dragonsinth** [comment]
> @dragonsinth good point, I can cut a release today.

I didn't mean today, it's Thanksgiving 😆

**Comment by gpassini** [comment]
Not in Canada! Ours is earlier 😄 🇨🇦

**Comment by dragonsinth** [comment]
> Not in Canada! Ours is earlier 😄 🇨🇦

Ahh right!

**Comment by gpassini** [comment]
Small update: we're almost ready to release a new version, we just need to fix our `goreleaser` configuration 🤞 
* https://github.com/fullstorydev/grpcui/pull/349
