### ISSUE TITLE
Official Docker image

### ISSUE THREAD

**Issue by augi** [fullstorydev/grpcui#35]
There are currently [three Docker images that wrap grpcui](https://hub.docker.com/search?q=grpcui&type=image).

It would be nice to have also an _official_ Docker image that would be automatically released when new release of grpcui is made.

**Comment by jhump** [comment]
@augi, you'll find the official one here: https://hub.docker.com/r/fullstorydev/grpcui

**Comment by augi** [comment]
Perfect, thank you! 👍

**Comment by Kernald** [comment]
Small note on that: it's a common practice to push the latest image with both its actual tag and the tag `latest`. Definitely not a big deal though, thanks for publishing it!

**Comment by danieleades** [comment]
note that the official docker image doesn't support a way to set the port of the gRPC server (it's hardcoded to 8080).
If you want to use a different port, you can use this- https://hub.docker.com/r/wongnai/grpcui

**Comment by jhump** [comment]
@danieleades, why would it matter what port it listens on inside the container? You can always expose it via a different port:

```
# expose grpcui on port 8987
docker run -p8987:8080 fullstorydev/grpcui 172.17.0.1:8980
```

**Comment by danieleades** [comment]
> @danieleades, why would it matter what port it listens on inside the container? You can always expose it via a different port:
> 
> ```
> # expose grpcui on port 8987
> docker run -p8987:8080 fullstorydev/grpcui 172.17.0.1:8980
> ```

Because you might want to expose it to a different container, rather than the host.

**Comment by jhump** [comment]
@danieleades, I see. So this is for running multiple containers in the same network, like in a Kubernetes pod, and needing to avoid port conflicts with other containers?

**Comment by jhump** [comment]
@danieleades, I just tested, and it works fine with the `fullstorydev/grpcurl` image to customize the port via specifying a `-port` argument. It will override the earlier argument that is baked into the container entrypoint.

**Comment by danieleades** [comment]
@jhump are you referring to the upstream grpc port the UI is listening to, or the port on which it is serving the UI? It's the listening port I need to customise.
Secondly, how are you passing in this argument? I'm using docker-compose (or equivalently, kubernetes, "docker app", etc). Are you simply overriding the entrypoint on the command line? This is fine for single container deployments, but a more scalable solution would be to use an environment variable. Basically the way the linked container is set up.

**Comment by jhump** [comment]
>  are you referring to the upstream grpc port the UI is listening to, or the port on which it is serving the UI

For the former, I think you meant "grpc port the remote service is listening to", right?

I am suggesting how to customize both. You can pass the remote service host:port (for the former) _and_ you can suplply a `-port` arg (for the latter). With kubernetes, you just provide parameters in the container definition of a pod spec. With docker-compose, use the `command` configuration option. With `docker run ...`, just append the arguments.
