### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by JensRantil** [fullstorydev/grpcui#39]
```
$ go get github.com/fullstorydev/grpcui
...
$ go install github.com/fullstorydev/grpcui/cmd/grpcui
# github.com/fullstorydev/grpcurl
../go/src/github.com/fullstorydev/grpcurl/grpcurl.go:600:4: undefined: grpc.WithContextDialer
```

**Comment by jhump** [comment]
@JensRantil, you are using an old version of the gRPC library. A few things could fix that:

1. Try using `go get -u ...` which will update all dependencies.
2. Use Go modules. If you are using Go 1.11 or above, just do `GO111MODULE=on go install ...`.
3. Just update the one dependency `"google.golang.org/grpc"` (though you may encounter others that already exist in your `GOPATH` and are also too old). If you look at `go.mod`, you'll see the required versions.
