### ISSUE TITLE
Reflection throws error when targeting Google.Protobuff 3.9

### ISSUE THREAD

**Issue by mihalios** [fullstorydev/grpcui#45]
@jhump this is not an issue against your project but I figured it's worth mentioning here in case others have upgraded to Protobuff 3.9 and can't run GRPCUI.

In short, if a GRPC server gets upgraded to use Protobuf 3.9 (latest version, released 4 days ago)  and you try to run GRPCUI against it, reflection fails with error:

`Method not found: 'Google.Protobuf.FieldCodec<Google.Protobuf.ByteString> Google.Protobuf.FieldCodec.ForBytes(UInt32)'.`

I believe this is a result of an issue introduced in 3.9 and that is documented by the Protobuf team [here](https://github.com/protocolbuffers/protobuf/issues/6379).

**Comment by jhump** [comment]
Thanks for the heads up, @mihalios

**Comment by mihalios** [comment]
Fixed in 3.9.1 (3.9.0 was removed from nuget).
