### ISSUE TITLE
Include protobuf comments in web form

### ISSUE THREAD

**Issue by bjaglin** [fullstorydev/grpcui#50]
As an operator without access to the original protos, I would like to see [protobuf comments](https://github.com/protocolbuffers/protobuf/blob/044c766/src/google/protobuf/descriptor.proto#L855-L857) within the `grpcui` web form in order to have more context when entering data.

**Comment by bjaglin** [comment]
From a quick look, it looks like this wouldn't be too hard, as https://github.com/jhump/protoreflect exposes this data (at least on the server-side). I'd be willing to try a PR if this feature makes sense.

**Comment by jhump** [comment]
@bjaglin, I heartily agree. I'm surprised I had not already filed an issue for this.

Unfortunately, the "on rails" method for using grpcui, which involves using server reflection, won't get any benefit: `protoc` generators and plugins almost always strip comments from the descriptors that get embedded into programs (all of the official ones do anyway). So when querying the server for descriptors, the server won't returns files that have source info. So this will really only work when pointing grpcui at proto source files _or_ if you have descriptor set files that include source info.

Anyhow, if you do put up a PR, I'd certainly be happy to review it.

**Comment by bjaglin** [comment]
@jhump Thanks for the prompt feedback - I did not consider the limitation with server reflection, as [the server-side gRPC runtime we use does not support it](https://github.com/akka/akka-grpc/issues/380)... I will try to find some time to work on a PR over the next few weeks!

**Comment by bdejong** [comment]
Did this ever make it into a PR?

**Comment by bjaglin** [comment]
> Did this ever make it into a PR?

Nope, unfortunately I didn't get the chance to start.

**Comment by patkoscsaba** [comment]
I would also like to see this implemented. Thanks.

**Comment by n0v1** [comment]
I just created a PR that implements this feature. Please test and/or suggest improvements.

**Comment by jhump** [comment]
Resolved in #166.
