### ISSUE TITLE
Nodejs supporting 

### ISSUE THREAD

**Issue by sergey-telpuk** [fullstorydev/grpcui#55]
gRPC server is written by NodeJS. I have an issue with connecting. 
```
Failed to compute set of methods to expose: server does not support the reflection API
```

**Comment by jhump** [comment]
@sergey-telpuk, grpcui supports all gRPC servers. But if a server does not expose the reflection service (which could be the case for any backend implementation, including Go, C++, Java, etc), you have to provide it the `.proto` source files using `-proto` (and maybe `-import-path`) flags.

As far as making your service actually expose the reflection service, that is clearly outside of the scope of grpcui. It is being tracked in the repo that provides official Node support for gRPC: https://github.com/grpc/grpc-node/issues/79.

**Comment by jhump** [comment]
@sergey-telpuk, I don't think this is a grpcui issue. See my above response for how you can work-around the issue until the Node gRPC runtime supports reflection.

I would like to close this issue. Was my reply above adequate?

**Comment by sergey-telpuk** [comment]
@jhump Yeap, close it
