### ISSUE TITLE
Error: Cant find package

### ISSUE THREAD

**Issue by ameetchhatwal** [fullstorydev/grpcui#71]
Due to recent changes to introduce the github.com/pkg/browser and golang.org/x/crypto/ssh/terminal 
 I get error while build it from dockerfile ```Step 8/14 : RUN go install github.com/fullstorydev/grpcui/cmd/grpcui
 ---> Running in dbe088db5baa
src/github.com/fullstorydev/grpcui/cmd/grpcui/grpcui.go:25:2: cannot find package "github.com/pkg/browser" in any of:
	/usr/local/go/src/github.com/pkg/browser (from $GOROOT)
	/go/src/github.com/pkg/browser (from $GOPATH)
src/github.com/fullstorydev/grpcui/cmd/grpcui/grpcui.go:26:2: cannot find package "golang.org/x/crypto/ssh/terminal" in any of:
	/usr/local/go/src/golang.org/x/crypto/ssh/terminal (from $GOROOT)
	/go/src/golang.org/x/crypto/ssh/terminal (from $GOPATH)```

Can you please help figuring out why is this happening.

**Comment by jhump** [comment]
What version of Go/image are you using? Are you using Go modules? It would be more helpful if you could provide enough details for me to repro.

**Comment by ameetchhatwal** [comment]
I am using this Dockerfile to build a container and launch the grpcui 
`FROM golang:1.12.4-stretch

ENV TINI_VERSION v0.18.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini
#Just Download the GO package
RUN go get -d github.com/fullstorydev/grpcui
# Copy the bindata for custom header and query param support
COPY grpcui/webform/bindata.go /go/src/github.com/fullstorydev/grpcui/internal/resources/webform/
# Install the updated GO package
RUN go install github.com/fullstorydev/grpcui
# Install the cmd line binary
RUN go install github.com/fullstorydev/grpcui/cmd/grpcui

COPY grpcui/scripts/ /usr/local/scripts/
RUN chmod +x /usr/local/scripts/*.sh

ENV PATH /usr/local/scripts/:$PATH

EXPOSE 31415

ENTRYPOINT ["/tini", "-s", "--"]
CMD ["start.sh"]
`

This use to work, until last week and was throwing error I posted above in the step 
`RUN go install github.com/fullstorydev/grpcui/cmd/grpcui`
and upon looking there was a change made, and it seem related to the new imports in grpcui cmd.

Please let me know if you need more info. My go local machine go version is 1.14.3. I am not using go modules.

**Comment by jhump** [comment]
@ameetchhatwal, looks like the issue is the `go get` step. You are only doing `go get` for the base package, not for the `cmd/grpcui` sub-package. That means that `go get` is _not_ crawling and installing the deps for the command, only for the `github.com/fullstorydev/grpcui` package (which does not depend on those two items, hence they are not present).

Either get the right package:
```
go get -d github.com/fullstorydev/grpcui/cmd/grpcui
```
Or get all of 'em:
```
go get -d github.com/fullstorydev/grpcui/...
```

**Comment by ameetchhatwal** [comment]
That makes sense. I will try that. Thanks a lot.

**Comment by josephharrington** [comment]
I ran into this as well. Should the install doc be updated to reflect this?
https://github.com/fullstorydev/grpcui#installation

**Comment by plunkettscott** [comment]
Followed the installation and had the same problem too. I think the docs should be updated to reflect the proper `go get` command for those looking for a copy/paste install.

**Comment by plunkettscott** [comment]
I can PR it if you want.

**Comment by jhump** [comment]
@plunkettscott, thanks for the offer. But it is a tiny change, so I just made it. Sorry for the confusion.

**Comment by plunkettscott** [comment]
Thanks @jhump
