### ISSUE TITLE
unable to send empty strings

### ISSUE THREAD

**Issue by horacimacias** [fullstorydev/grpcui#75]
I have a service where a certain field is a string and can be empty.

If I send a request through grpcui using an empty string, my grpc service does not receive that field at all.

I'd expect to see a difference between:
 * field checkbox enabled in grpui but field empty: my grpc service should receive empty value for that field
![image](https://user-images.githubusercontent.com/1333208/84369827-b7e86300-abd7-11ea-8b25-ef548dd69160.png)

vs
 * field checkbox not enbled in grpui: my grpc service should not receive such field

![image](https://user-images.githubusercontent.com/1333208/84369854-c2a2f800-abd7-11ea-90fc-0844d7496479.png)

in my case I'm seeing same received parameters on my grpc server.

Is there any way to be able to send empty strings?

**Comment by horacimacias** [comment]
just to clarify, on the the browser->grpcui communication, I do see a difference:

```json
{"timeout_seconds":0,"metadata":[],"data":[{"id":""}]}
```
vs

```json
{"timeout_seconds":0,"metadata":[],"data":[{}]}
```

but on the grpcui->my grpc server communication I don't see a difference.

**Comment by jhump** [comment]
Is this a proto2 message? If not, how is it you are trying to distinguish?

**Comment by horacimacias** [comment]
Sorry @jhump, the problem must have been somewhere else (likely between the chair and the monitor =:O) as I now do the same test again and I see what I'd expect.

This is proto3, and I was getting an error that looked like the server complaining about the field being not present (not about being empty, but about the field not being there at all). Again it must have been me misreading the error back.

Testing again I see it all good now, so sorry for the confusion; nothing to fix here.
