### ISSUE TITLE
Input fixed request metadata when execute grpcui

### ISSUE THREAD

**Issue by kajebiii** [fullstorydev/grpcui#87]
Hi!
In our project, 
All requests require token in request-metadata for security

There is node A (grpc server), node B (grpcui)
node A and node B knows the token (by environment variable).
But user that connected to node B don't know the token.

User can't use grpcui (b/c node A require token for all requests, and they don't know the token)

So I want when execute grpcui, can input fixed request metdata.

For example, make new parameter -metadata key:value
```bash
grpcui -metadata token:password -metadata other_token:other_password localhost:8888
```

Thanks for reading.

**Comment by jhump** [comment]
I think this is a duplicate of #85.

**Comment by jhump** [comment]
#88 adds support for `-default-header` flags which can be used to define request header metadata that will be included by default in the gRPCui form.
