### ISSUE TITLE
grpcui: command not found

### ISSUE THREAD

**Issue by Serena-Xu** [fullstorydev/grpcui#96]
I followed **Installation** and installed `grpcui`
```
go get github.com/fullstorydev/grpcui/...
go install github.com/fullstorydev/grpcui/cmd/grpcui
```

I also setted grpcui in my $PATH. I even tried with downloading this repo and `make install`. But I keep getting error `grpcui: command not found`. Anyone could help ?

**Comment by jhump** [comment]
@Serena-Xu, this sounds like your `PATH` is not setup for working with Go code.

If you have a `GOPATH` env var defined, then you also want `$GOPATH/bin` in your `PATH`. If you do _not_ have a `GOPATH`, then you need `$HOME/go/bin` in your `PATH`. That's just how the Go tool works, in general, when you are using it to install binaries built from Go source.

**Comment by Serena-Xu** [comment]
> @Serena-Xu, this sounds like your `PATH` is not setup for working with Go code.
> 
> If you have a `GOPATH` env var defined, then you also want `$GOPATH/bin` in your `PATH`. If you do _not_ have a `GOPATH`, then you need `$HOME/go/bin` in your `PATH`. That's just how the Go tool works, in general, when you are using it to install binaries built from Go source.

Set up `$HOME/go/bin` in your `PATH` works.
